        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 24 17:39:16 2015
        MODULE VEGETATION_HEIGHT__genmod
          INTERFACE 
            SUBROUTINE VEGETATION_HEIGHT
            END SUBROUTINE VEGETATION_HEIGHT
          END INTERFACE 
        END MODULE VEGETATION_HEIGHT__genmod
