        !COMPILER-GENERATED INTERFACE MODULE: Thu Jun 25 15:18:11 2015
        MODULE VEGETATION_HEIGHT__genmod
          INTERFACE 
            SUBROUTINE VEGETATION_HEIGHT
            END SUBROUTINE VEGETATION_HEIGHT
          END INTERFACE 
        END MODULE VEGETATION_HEIGHT__genmod
