        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 23 12:20:38 2015
        MODULE VEGETATION_HEIGHT__genmod
          INTERFACE 
            SUBROUTINE VEGETATION_HEIGHT
            END SUBROUTINE VEGETATION_HEIGHT
          END INTERFACE 
        END MODULE VEGETATION_HEIGHT__genmod
